---
- name: Exercise 26 - Show Host Facts
  hosts: all
  gather_facts: yes

  tasks:
    - name: Show basic info
      debug:
        msg: |
          Hostname: {{ ansible_hostname }}
          OS: {{ ansible_distribution }} {{ ansible_distribution_version }}
          IP: {{ ansible_default_ipv4.address }}
