---
- name: Jinja2 Exercise 47 - Dynamic /etc/hosts
  hosts: all
  gather_facts: true

  tasks:
    - name: Ensure output dir exists on localhost
      delegate_to: localhost
      ansible.builtin.file:
        path: /tmp/jinja_exercises
        state: directory

    - name: Render dynamic hosts file
      delegate_to: localhost
      ansible.builtin.template:
        src: templates/hosts.j2
        dest: /tmp/jinja_exercises/ex5_output.txt
